[[sources]]
type = "github"
owner = "NixOS"
repo = "hydra"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "offen"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "pixelfed"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "lightmeter"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "openpgp-ca"

[[sources]]
type = "github"
owner = "ngi-nix"
repo = "weblate"

[[sources]]
type = "github"
owner = "fort-nix"
repo = "nix-bitcoin"

[[sources]]
type = "gitlab"
owner = "pi-lar"
repo = "neuropil"

[[sources]]
type = "github"
owner = "tweag"
repo = "nickel"

[[sources]]
type = "github"
owner = "pinpox"
repo = "nixos"

[[sources]]
type = "github"
owner = "Mic92"
repo = "sops-nix"

[[sources]]
type = "github"
owner = "PaddiM8"
repo = "kalker"

[[source]]
type = "github"
owner = "pta2002"
repo = "nixvim"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "nix-cargo-integration"

[[sources]]
type = "github"
owner = "yusdacra"
repo = "rust-nix-templater"

[[sources]]
type = "github"
owner = "srid"
repo = "emanote"

[[sources]]
type = "git"
url = "git+https://git.sr.ht/~kerstin/sway-timetracker?ref=main"

[[sources]]
type = "github"
owner = "PolyMC"
repo = "PolyMC"

[[sources]]
type = "gitlab"
owner = "simple-nixos-mailserver"
repo = "nixos-mailserver"

[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/stream-alert-bot?ref=main"

[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/python-trovo?ref=main"

[[sources]]
type = "git"
url = "git+https://codeberg.org/wolfangaukang/multifirefox?ref=main"

[[sources]]
type = "github"
owner = "juliosueiras-nix"
repo = "nix-security"

[[sources]]
type = "github"
owner = "SpyHoodle"
repo = "pridefetch"
