name: "Nixpkgs: Hourly import to Elasticsearch"

on:

  pull_request:
  schedule:
  - cron: '0 * * * *'

jobs:

  import-channel:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        channel:
          - unstable
          - 21.05
          - 20.09

    env:
      RUST_LOG: debug
      FI_ES_EXISTS_STRATEGY: abort
      FI_ES_URL: ${{ secrets.ELASTICSEARCH_URL }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Nix
      uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v10
      with:
        name: nixos-search
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Install unstable channel
      run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        nix-channel --update

    - name: Installing jq
      run: |
        nix-env -iA nixpkgs.nixFlakes nixpkgs.jq

    - name: Building import_scripts
      run: |
        nix build ./#packages.x86_64-linux.flake_info

    - name: Import ${{ matrix.channel }} channel
      run: |
        ./result/bin/flake-info --push --elastic-schema-version=$(cat ./VERSION) nixpkgs ${{ matrix.channel }}
      if: github.repository == 'NixOS/nixos-search'

    - name: Warmup ${{ matrix.channel }} channel
      run: |
        curl ${{ secrets.ELASTICSEARCH_URL }}/latest-$(cat VERSION)-nixpkgs-${{ matrix.channel }}/_search | jq '.took'
        curl ${{ secrets.ELASTICSEARCH_URL }}/latest-$(cat VERSION)-nixpkgs-${{ matrix.channel }}/_search | jq '.took'
        curl ${{ secrets.ELASTICSEARCH_URL }}/latest-$(cat VERSION)-nixpkgs-${{ matrix.channel }}/_search | jq '.took'
      if: github.repository == 'NixOS/nixos-search'
